### PR TITLE
Captive Portal and Joinme as a library

### PR DESCRIPTION
**Pull request by Eroc33**
This re-implements joinme as a library.
The files for joinme have been moved into the waterelf32 project folder as this is the only easy way I could find mentioned online to use them as a library.
Joinme currently isn't handling connecting to WiFi APs, but is handling captive portal (though this is currently untested for iPhone, but is confirmed working on android 7.1.1 (Android N) ).

(Joinme is currently using a c style interface but if you prefer i could convert it to use an object for a c++ style interface).

### CODE REVIEW

**Comment by Eroc33** [comment]
I'm thinking that perhaps `handle_wifi` and `handle_wfchz` should also be handled be joinme instead of the main sketch? Also is this good how it is or should it be synchronous like the original lua joinme (where you have to join a wifi hotspot to get to the main program)

**Comment by layerzerolabs** [comment]
Good questions but to answer them I think we need to consider #8
refactoring - makes sense to refactor into a new design rather than do it
twice...

On 18 Nov 2017 18:04, "Euan Rochester" <notifications@github.com> wrote:

I'm thinking that perhaps handle_wifi and handle_wfchz should also be
handled be joinme instead of the main sketch? Also is this good how it is
or should it be synchronous like the original lua joinme (where you have to
join a wifi hotspot to get to the main program)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hamishcunningham/fishy-wifi/pull/19#issuecomment-345459543>,
or mute the thread

**Review by hamishcunningham — APPROVED** [review]
Looks good! I'll merge. Then could you change the few comments that are > 80 characters to break at <= 79? (This makes diffs easier to work with in line-based environments like the shell, and in my editor.) Thanks!

**Comment by Eroc33** [comment]
Do you want me to open a new PR for the comment changes? or should I just push them to master?

**Comment by hamishcunningham** [comment]
Just push directly to master, tnx!
h

**Pull request merged**
