### PR TITLE
Add delay before initialising DHT22

### LINKED ISSUE #15: Waterelf32 startPeripherals not detecting DHT22
As noted in https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf, the DHT22 has an average sensing period of 2s.

The function `startPeripherals` will occasionally not detect the DHT22 as a reading has not yet been made before initialising the sensor with `dht.begin()`:
https://github.com/hamishcunningham/fishy-wifi/blob/c7e3cb415f0ee15786c1d1fe610efdc433e5f889/ardesp/waterelf32/waterelf32.ino#L816-L823

Adding a `delay(2000)` before line 816 seems to work as a fix for this.

### PR DESCRIPTION
**Pull request by cgmcintyr**
- Fixes #15
- Defines BUILTIN_LED as pin 13

### CODE REVIEW

**Comment by layerzerolabs** [comment]
I see `BUILTIN_LED` defined in .../Arduino/hardware/espressif/esp32/variants/feather_esp32/pins_arduino.h 
`static const uint8_t LED_BUILTIN = 13;`
`#define BUILTIN_LED  LED_BUILTIN // backward compatibility`
I don't understand the value of (re?)defining this in the sketch?

**Comment by cgmcintyr** [comment]
Sorry, this may be to do with not including the `Arduino/hardware/espressif/esp32/variants/feather_esp32/pins_arduino.h`, I'll be sure to remove the definition of `BUILTIN_LED` from the pull request.

**Comment by layerzerolabs** [comment]
Ah yes, I remember you saying you were also using the expressif IDF - fundamentally better I'm sure but for us the main advantage of the arduino IDE is that novices can hack our stuff, widening up participation...

**Comment by hamishcunningham** [comment]
Happy to merge but pending discussion on #15 ...?

**Pull request closed without merging**
