### PR TITLE
Add hotfixed DHT.h that disables interrupts on ESP32

### LINKED ISSUE #15: Waterelf32 startPeripherals not detecting DHT22
As noted in https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf, the DHT22 has an average sensing period of 2s.

The function `startPeripherals` will occasionally not detect the DHT22 as a reading has not yet been made before initialising the sensor with `dht.begin()`:
https://github.com/hamishcunningham/fishy-wifi/blob/c7e3cb415f0ee15786c1d1fe610efdc433e5f889/ardesp/waterelf32/waterelf32.ino#L816-L823

Adding a `delay(2000)` before line 816 seems to work as a fix for this.

### PR DESCRIPTION
**Pull request by cgmcintyr**
Closes #15

Thanks to @Eroc33 for pointing out that the issue was centered around the disabling of the esp32's interrupts!

### CODE REVIEW

**Comment by cgmcintyr** [comment]
### Test

As a quick test I checked startup of the DHT22 20 times with waterelf32 code without commit 4d27eac having been applied, and 20 times with commit 4d27eac being applied. 

For the test I plugged in the DHT22, HR-SR04, TSL-2591, RF LINK TX, and DS18B20.

### Results 

See table below for percentage of 20 times that DHT22 was detected in `startPeripherals` function of waterelf32:

|Before Applying Commit|After Applying Commit|
|------|-----|
|0%|100%|

### Conclusion

For the ESP32 this change is necessary for the DHT22 to start up consistently (and perhaps at all).

**Comment by layerzerolabs** [comment]
Great stuff! tiny point - if you kept the same library order in waterelf32 then wouldn't the change from <DHT.h> to "DHT.h" would be more obvious as a single line on the diff?
Also for completeness I would suggest adding a comment alongside the critical lines - just a judicious word or two - perhaps referencing https://github.com/espressif/arduino-esp32/issues/832? And add a line at the beginning after the original authors bit to say modified by x because of bugs y and z so that we can just squint at the code in a few months time and immediately be reminded why we've got a modified copy...
And having previously found https://github.com/adafruit/DHT-sensor-library/issues/48#issuecomment-197773684 - are you thinking of doing a separate pr for that? Or does this interrupt fix somehow resolve the incorrect initialisation timing issue?

**Comment by cgmcintyr** [comment]
Yes, I just sorted the includes out of habit - I'll change them back to make the changes more clear! I'll also add in some comments to explain the changes.

With regards to https://github.com/adafruit/DHT-sensor-library/issues/48#issuecomment-197773684, the problems in the thread seem to be centered around sensor inaccuracy. As #15 concerns detection it may be better to open a new issue to check that the DHT is reading accurately and have a seperate pr if necessary.

**Comment by layerzerolabs** [comment]
Seems to me most folks are having approx 5% occasional NaNs and read failures in the adafruit bug thread, detection is just starting the sensor and taking a reading of both humidity and temperature.
But I can't argue with your experimental results table - if you've done 20 trials then that's 40 readings without NaNs - I can't remember enough stats to calculate the confidence interval but it must be quite high. On the other hand, would be trivial to run it for a couple of min to generate 100 readings and see if they're all good... would shut me up and close #15....

**Comment by cgmcintyr** [comment]
<details><p><summary>100 non-NaN readings :)</summary>

```
startPeripherals...
Soft AP started
AP SSID: WaterElf-BC130CC40A24; IP address(es): local=0.0.0.0; AP=192.168.99.1
joinme will direct captured clients to: 192.168.99.1
joinme captive dns server started
joinme http handlers added
HTTP server started
doing flow controller and mcp init...
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: 26.25 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139188
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.31 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.37 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.50 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.80 C, Humidity: 43.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.50 C, 
Air Temp: 21.90 C, Humidity: 67.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.90 C, Humidity: 67.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.00 C, Humidity: 73.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.00 C, Humidity: 73.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.00 C, Humidity: 70.30 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.56 C, 
Air Temp: 22.00 C, Humidity: 70.30 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.56 C, 
Air Temp: 21.90 C, Humidity: 66.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.90 C, Humidity: 66.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.90 C, Humidity: 70.80 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 21.90 C, Humidity: 70.80 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 90.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 90.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.62 C, 
Air Temp: 22.10 C, Humidity: 81.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 81.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 78.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 78.70 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 75.40 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.10 C, Humidity: 75.40 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.40 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.40 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.69 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.69 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.80 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.69 C, 
Air Temp: 22.70 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.70 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.70 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 170 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.70 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.60 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.60 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.75 C, 
Air Temp: 22.60 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.60 C, Humidity: 99.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139168
Water temp: -127.00 C, 
Air Temp: 22.50 C, Humidity: 94.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.75 C, 
Air Temp: 22.50 C, Humidity: 94.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.50 C, Humidity: 90.10 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.75 C, 
Air Temp: 22.50 C, Humidity: 90.10 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.75 C, 
Air Temp: 22.40 C, Humidity: 85.10 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.40 C, Humidity: 85.10 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.40 C, Humidity: 81.50 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.81 C, 
Air Temp: 22.40 C, Humidity: 81.50 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.81 C, 
Air Temp: 22.30 C, Humidity: 79.50 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 79.50 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 78.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 78.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 77.30 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 77.30 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.87 C, 
Air Temp: 22.30 C, Humidity: 74.80 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 74.80 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 73.40 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 73.40 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.20 C, Humidity: 70.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: 26.94 C, 
Air Temp: 22.20 C, Humidity: 70.90 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 68.50 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 68.50 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 67.20 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 67.20 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 65.40 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 65.40 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 63.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 63.60 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
Water temp: -127.00 C, 
Air Temp: 22.30 C, Humidity: 62.30 %RH, 
Light: 32 Lux
Water Level: 0 cm, 
Water Level: 0 cm, 
Water Level: 0 cm, 
getAnalog
free heap=139192
```

</p></details>

**Review by layerzerolabs — APPROVED** [review]
Awesome!

**Pull request merged**
